// Landing-page content model. Two sources feed the same shape:
//   - hf-media.json  → Higgsfield's own landing media, hotlinked (review-only,
//                      generated by scripts; off unless the file says enabled)
//   - the fallback   → stills generated by this app + free-license clips
import raw from "./hf-media.json";
import { PRESETS, presetThumbUrl } from "./presets";
import { PRESET_CLIPS, PROJECT_CLIPS, GENJUTSU_CLIPS, FEATURE_CLIPS, clipUrl } from "./clips";

export interface FeatureCard { title: string; body: string; href: string; poster: string; video: string }
export interface EffectTile { id: string; name: string; poster: string; video: string }
export interface RowItem { poster: string; video?: string; author: string }
export interface Row { title: string; blurb: string; href: string; ratio: string; items: RowItem[] }
export interface Project { slug: string; title: string; poster: string; hls?: string; video?: string }
export interface Landing {
  source: "higgsfield" | "generated";
  feature: FeatureCard[];
  promo: { poster: string; video: string };
  effects: EffectTile[];
  genjutsu: string[];
  rows: Record<"seedance25" | "gptImage2" | "marketing" | "seedance2" | "soulCinema" | "soul2", Row>;
  projects: Project[];
  banners?: { supercomputer: Record<string, string>; canvas: Record<string, string>; photodump: Record<string, string> };
  moreFeatures: { label: string; href: string }[];
  footer: { title: string; links: string[] }[];
}

type HfJson = Partial<Landing> & { enabled?: boolean };

const MORE_FEATURES = [
  ["Cinema Studio", "/ai/video"], ["Visual Effects", "/effects"], ["Higgsfield Soul", "/ai/image?model=soul_2"], ["Kling 3.0", "/ai/video?model=kling_3"],
  ["Camera Controls", "/effects"], ["Viral", "/effects"], ["Action movements", "/ai/video?preset=high_flip"], ["Commercial", "/ai/video?preset=smash_and_grab"],
  ["MiniMax H3", "/ai/video?model=minimax_h3"], ["Seedance 2.5", "/ai/video?model=seedance_2_5"], ["Community", "/"], ["Recraft V4.1", "/ai/image?model=recraft_v4_1"],
  ["Seedream 4.5", "/ai/image?model=seedream_4_5"], ["Nano Banana", "/ai/image?model=nano_banana"], ["Soul Cinema", "/ai/image?model=soul_cinema"], ["GPT Image 2", "/ai/image?model=gpt_image_2"],
  ["Google Veo", "/ai/video?model=veo"], ["Grok Imagine 1.5", "/ai/video?model=grok_imagine_1_5"], ["Wan 3.0", "/ai/video?model=wan_3"], ["Sora 2", "/ai/video?model=sora_2"],
  ["Genjutsu", "/ai/video?model=genjutsu"], ["Effects presets", "/effects"], ["Assets", "/asset/all"], ["Pricing", "/pricing"],
].map(([label, href]) => ({ label, href }));

const FOOTER = [
  { title: "Create", links: ["AI Video", "AI Image", "Edit Image", "Inpaint", "Upscale", "Mixed Media", "AI Face Swap", "AI Influencer", "Apps"] },
  { title: "Video Models", links: ["Seedance 2.5", "Seedance 2.0", "Kling 3.0", "Sora 2", "Veo", "Wan 3.0", "Grok Imagine 1.5", "Gemini Omni Flash"] },
  { title: "Image Models", links: ["Nano Banana", "FLUX", "Seedream 5", "GPT Image 2"] },
  { title: "Studios", links: ["Cinema Studio", "Marketing Studio", "Lipsync Studio", "Photodump Studio", "Fashion Factory", "UGC Factory", "Canvas"] },
  { title: "Soul", links: ["Soul 2.0", "Soul ID Character", "Soul Cinema"] },
  { title: "Platform", links: ["Supercomputer", "MCP/CLI", "Collab", "Games", "Reference Extension"] },
  { title: "Resources", links: ["Blog", "Creator Hub", "Help Center", "Academy", "Prompt Guide"] },
  { title: "Company", links: ["About", "Trust", "Enterprise", "Team", "Pricing", "Careers", "Contact"] },
  { title: "Community", links: ["Community", "Contests", "Creator Partners"] },
];

// Community-row prompts for the generated fallback; each row reads like the
// model it advertises.
const ROW_PROMPTS: Record<string, { subjects: string[]; style: string; w: number; h: number }> = {
  seedance25: { subjects: ["a woman in a red coat crossing a rainy street at night", "a motorcyclist in neon tunnel light", "a child running through a wheat field at sunset", "a boxer under a single tungsten bulb", "a dancer on a wet rooftop, city lights below", "an astronaut walking through a shopping mall"], style: "cinematic film still, 35mm, dramatic light", w: 576, h: 1024 },
  gptImage2: { subjects: ["minimal poster with the word SIGNAL in bold type", "a magazine cover, headline 'FUTURE', studio portrait", "a product label for sparkling water, legible text", "an infographic-style map of a fictional city", "a retro cereal box with playful lettering", "a movie poster with the title 'NIGHT LINE'"], style: "clean typography, crisp product render", w: 768, h: 1024 },
  marketing: { subjects: ["a matte black sneaker floating above wet concrete", "a perfume bottle on a marble plinth in morning light", "a can of cold brew with condensation on a picnic table", "a smartwatch on a runner's wrist at dawn", "a pair of sunglasses on a sun-bleached dashboard", "a lipstick on a mirrored surface with neon reflections"], style: "commercial product shot, studio rim light", w: 1024, h: 576 },
  seedance2: { subjects: ["a vintage car drifting through a desert town", "a surfer at golden hour, drone shot", "a chef plating a dish in a busy kitchen", "a street market in the rain, umbrellas", "a snowboarder carving powder", "a train crossing a viaduct in fog"], style: "cinematic wide shot, anamorphic", w: 1024, h: 576 },
  soulCinema: { subjects: ["two figures on a foggy pier at dawn", "a woman in a yellow raincoat under neon signs", "a man in a diner booth at 3am", "a girl on a bus looking out a rainy window", "a couple dancing in an empty parking lot", "a detective under a flickering streetlamp"], style: "cinematic still, anamorphic, teal and amber grade", w: 1024, h: 576 },
  soul2: { subjects: ["editorial fashion portrait, oversized wool coat", "close-up portrait, freckles, silver hoop earring", "a model in a brutalist courtyard, overcast", "streetwear look on a rooftop, golden hour", "a portrait in a vintage car, film grain", "a runway walk, harsh flash photography"], style: "editorial fashion photograph, natural skin texture, 35mm film grain", w: 768, h: 1024 },
};

function hash(s: string) {
  let h = 7;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h;
}
function genUrl(prompt: string, w: number, h: number, seed: string) {
  const q = new URLSearchParams({ width: String(w), height: String(h), seed: String(hash(seed) % 100000), model: "flux", nologo: "true", safe: "true", enhance: "false" });
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?${q.toString()}`;
}

const AUTHORS = ["yernaz", "smartbeetle", "zhanay", "artificial_penguin", "gaziziz", "jighit", "rococo_pen", "madi_k", "daulett", "wer", "young_drill", "piffle_jack"];

function generatedRow(key: keyof typeof ROW_PROMPTS, title: string, blurb: string, href: string, videoIds?: number[]): Row {
  const p = ROW_PROMPTS[key];
  const items: RowItem[] = p.subjects.map((s, i) => ({
    poster: genUrl(`${s}, ${p.style}`, p.w, p.h, `${key}-${i}`),
    video: videoIds ? clipUrl(videoIds[i % videoIds.length]) : undefined,
    author: AUTHORS[(hash(key) + i) % AUTHORS.length],
  }));
  return { title, blurb, href, ratio: `${p.w}/${p.h}`, items };
}

function generated(): Landing {
  const byId = (id: string) => PRESETS.find((p) => p.id === id)!;
  return {
    source: "generated",
    feature: [
      { title: "Higgsfield Genjutsu", body: "One upload in. Endless new visions out.", href: "/ai/video?model=genjutsu", poster: presetThumbUrl(byId("world_morphing"), "wide"), video: clipUrl(FEATURE_CLIPS.genjutsu.id) },
      { title: "Higgsfield Effects", body: "Viral video presets — 20 camera and VFX recipes, free to try.", href: "/effects", poster: presetThumbUrl(byId("burning_man"), "wide"), video: clipUrl(FEATURE_CLIPS.effects.id) },
      { title: "Soul Cinema", body: "Cinema-grade stills. Anamorphic, moody, ready for the grade.", href: "/ai/image?model=soul_cinema", poster: presetThumbUrl(byId("nightline"), "wide"), video: clipUrl(FEATURE_CLIPS.soul_cinema.id) },
      { title: "Nano Banana 2", body: "Pro quality at Flash speed. 1 credit per image.", href: "/ai/image?model=nano_banana_2", poster: presetThumbUrl(byId("wild_ride"), "wide"), video: clipUrl(FEATURE_CLIPS.nano_banana.id) },
    ],
    promo: { poster: presetThumbUrl(byId("act_natural"), "wide"), video: clipUrl(PRESET_CLIPS.act_natural.id) },
    effects: PRESETS.filter((p) => p.featured && p.id !== "general").map((p) => ({ id: p.id, name: p.name, poster: presetThumbUrl(p, "card"), video: clipUrl(PRESET_CLIPS[p.id]?.id ?? PRESET_CLIPS.general.id) })),
    genjutsu: GENJUTSU_CLIPS.map((c) => clipUrl(c.id)),
    rows: {
      seedance25: generatedRow("seedance25", "Seedance 2.5", "The most advanced AI video model", "/ai/video?model=seedance_2_5", [40640, 33896, 26923, 23929, 33906, 40746]),
      gptImage2: generatedRow("gptImage2", "GPT Image 2", "4K images with near-perfect text rendering.", "/ai/image?model=gpt_image_2"),
      marketing: generatedRow("marketing", "Marketing Studio", "See what creators and brands are making with Marketing Studio.", "/ai/video?preset=smash_and_grab", [44555, 35576, 35540, 44541, 42037, 6754]),
      seedance2: generatedRow("seedance2", "Seedance 2.0", "Browse premium AI video generations from the Higgsfield community.", "/ai/video?model=seedance_2", [35230, 1367, 40957, 4332, 41375, 42039]),
      soulCinema: generatedRow("soulCinema", "Higgsfield Soul Cinema", "Explore the community gallery for stunning Soul Cinema creations.", "/ai/image?model=soul_cinema"),
      soul2: generatedRow("soul2", "Higgsfield Soul 2.0", "A culture-native photo model built for fashion, aesthetics, and creative expression.", "/ai/image?model=soul_2"),
    },
    projects: PROJECT_CLIPS.map((p) => ({ slug: p.title.toLowerCase().replace(/\s+/g, "-"), title: p.title, poster: "", video: clipUrl(p.clip.id) })),
    moreFeatures: MORE_FEATURES,
    footer: FOOTER,
  };
}

export function getLanding(): Landing {
  const hf = raw as HfJson;
  if (hf.enabled && hf.feature && hf.effects && hf.rows && hf.projects) {
    return { ...generated(), ...(hf as Landing), source: "higgsfield", moreFeatures: hf.moreFeatures ?? MORE_FEATURES, footer: hf.footer ?? FOOTER };
  }
  return generated();
}

/** Real effect media for a preset when the Higgsfield source is enabled. */
export function hfEffect(presetId: string): EffectTile | undefined {
  const hf = raw as HfJson;
  if (!hf.enabled) return undefined;
  return hf.effects?.find((e) => e.id === presetId);
}
